name: ListPid

options:
  bundleIdPrefix: com.List.Pid

targets:
  MyApp:
    type: application
    platform: iOS
    sources:
      - path: process.swift
      - path: processlist.h
      - path: processlist.c

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.List.Pid
      IPHONEOS_DEPLOYMENT_TARGET: 15.0
      SWIFT_OBJC_BRIDGING_HEADER: processlist.h

    info:
      path: MyApp/info.plist
